language: android
android:
components:
- tools
- platform-tools
- tools
- build-tools-25.0.3
- extra-google-m2repository
- extra-android-m2repository
- extra-google-android-support

- extra-google-google_play_services

- android-25

- sys-img-armeabi-v7a-android-25
licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

jdk: oraclejdk8

addons:
  sonarqube:
    branches: 
      - master
      - develop
      - issue_66

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
- ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=vboitsov-github -Dsonar.login=$SONAR_TOKEN
- ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
